const BUFFS = {
  0: "None",
  1: "Water Retain",
  2: "Growth Boost",
  3: "Weed Block",
  4: "Harvest Boost",
  5: "Quality Boost",
};

const CROPS = [
  {
    name: "-",
    buff: 0,
    time: 0,
    extra: 0,
    repeat: 0,
    base: 0,
    quality: 0,
    img: "#",
  },
  {
    name: "Apple",
    buff: 2,
    time: 12,
    extra: 6,
    repeat: 3,
    base: 64,
    quality: 96,
    img: "https://palia.wiki.gg/images/thumb/7/7d/Apple.png/65px-Apple.png",
  },
  {
    name: "Blueberry",
    buff: 2,
    time: 9,
    extra: 3,
    repeat: 3,
    base: 39,
    quality: 58,
    img: "https://palia.wiki.gg/images/thumb/9/9e/Blueberry.png/65px-Blueberry.png",
  },
  {
    name: "Carrot",
    buff: 3,
    time: 3,
    extra: 0,
    repeat: 0,
    base: 23,
    quality: 34,
    img: "https://palia.wiki.gg/images/thumb/c/c3/Carrot.png/65px-Carrot.png",
  },
  {
    name: "Corn",
    buff: 4,
    time: 5,
    extra: 0,
    repeat: 0,
    base: 40,
    quality: 60,
    img: "https://palia.wiki.gg/images/thumb/f/f8/Corn.png/65px-Corn.png",
  },
  {
    name: "Cotton",
    buff: 5,
    time: 5,
    extra: 0,
    repeat: 0,
    base: 45,
    quality: 67,
    img: "https://palia.wiki.gg/images/thumb/c/c3/Cotton.png/65px-Cotton.png",
  },
  {
    name: "Onion",
    buff: 3,
    time: 4,
    extra: 0,
    repeat: 0,
    base: 30,
    quality: 45,
    img: "https://palia.wiki.gg/images/thumb/5/51/Onion.png/65px-Onion.png",
  },
  {
    name: "Potato",
    buff: 1,
    time: 5,
    extra: 0,
    repeat: 0,
    base: 45,
    quality: 67,
    img: "https://palia.wiki.gg/images/thumb/c/c2/Potato.png/65px-Potato.png",
  },
  {
    name: "Rice",
    buff: 4,
    time: 3,
    extra: 0,
    repeat: 0,
    base: 27,
    quality: 40,
    img: "https://palia.wiki.gg/images/thumb/d/da/Rice.png/65px-Rice.png",
  },
  {
    name: "Spicy Pepper",
    buff: 5,
    time: 3,
    extra: 3,
    repeat: 0,
    base: 32,
    quality: 48,
    img: "https://palia.wiki.gg/images/thumb/9/97/Spicy_Pepper.png/65px-Spicy_Pepper.png",
  },
  {
    name: "Tomato",
    buff: 1,
    time: 4,
    extra: 2,
    repeat: 3,
    base: 23,
    quality: 34,
    img: "https://palia.wiki.gg/images/thumb/9/9d/Tomato.png/65px-Tomato.png",
  },
  {
    name: "Wheat",
    buff: 4,
    time: 4,
    extra: 0,
    repeat: 0,
    base: 33,
    quality: 49,
    img: "https://palia.wiki.gg/images/thumb/e/e2/Wheat.png/65px-Wheat.png",
  },
];

export { CROPS, BUFFS };
